{
  "name": "Coffee Machine Controller",
  "version": "1.0.0",
  "slug": "coffee_machine_controller",
  "description": "Control LaSpaziale S50-DEMO Robot coffee machines via Modbus RTU",
  "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
  "startup": "application",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 8000,
  "ingress_entry": "/",
  "panel_icon": "mdi:coffee",
  "panel_title": "Coffee Machine",
  "ports": {
    "8000/tcp": null
  },
  "ports_description": {
    "8000/tcp": "Web interface (not required when using ingress)"
  },
  "options": {
    "serial_port": "/dev/ttyUSB0",
    "baudrate": 9600
  },
  "schema": {
    "serial_port": "str",
    "baudrate": "int"
  },
  "devices": ["/dev/ttyUSB0", "/dev/ttyACM0"],
  "host_network": false,
  "webui": "http://[HOST]:[PORT:8000]"
}