# Generated by Django 5.2.5 on 2025-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('single_short', 'Single Short'), ('single_medium', 'Single Medium'), ('single_long', 'Single Long'), ('double_short', 'Double Short'), ('double_medium', 'Double Medium'), ('double_long', 'Double Long')], max_length=20)),
                ('group_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LaSpaziale S50-QSS', max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('port', models.CharField(max_length=50)),
                ('baudrate', models.IntegerField(default=9600)),
                ('number_of_groups', models.IntegerField(default=3)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('purge', 'Purge'), ('cleaning', 'Cleaning'), ('sensor_fault', 'Sensor Fault'), ('connection_issue', 'Connection Issue'), ('manual_stop', 'Manual Stop'), ('health_check', 'Health Check')], max_length=20)),
                ('group_number', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
